spring:
  application:
    name: media-worker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/media}
    username: ${SPRING_DATASOURCE_USERNAME:media}
    password: ${SPRING_DATASOURCE_PASSWORD:media}
  flyway:
    enabled: false
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: media-worker
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.example.media.common.events.MediaUploadedEvent
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

app:
  minio:
    endpoint: ${APP_MINIO_ENDPOINT:http://minio:9000}
    access-key: ${APP_MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${APP_MINIO_SECRET_KEY:minioadmin}
    bucket: ${APP_MINIO_BUCKET:media}
